DEFAULT_WRITE_MAX_RATE_PER_SECOND = 30
DEFAULT_OVERALL_WRITE_MAX_RATE_PER_SECOND = 60
POOL_TIMEOUT = 30
MAX_ALLOWED_FILE_SIZE = 1024**2  # 1MB


ACTIVE_EMOJI = "✅"
INACTIVE_EMOJI = "❌"
ADD_EMOJI = "➕"
EDIT_EMOJI = "✏️"
DELETE_EMOJI = "🗑️"
MORE_EMOJI = "🗎"
BACK_EMOJI = "⬅️"
IMAGE_EMOJI = "🖼️"
